# docker-compose.dev.yml
version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: warely-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: warely
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432" # Different port to avoid conflicts
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - warely-network

  # MongoDB Database
  mongodb:
    image: mongo:7-jammy
    container_name: warely-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: warely
    ports:
      - "27018:27017" # Different port to avoid conflicts
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - warely-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: warely-redis-dev
    restart: unless-stopped
    ports:
      - "6380:6379" # Different port to avoid conflicts
    volumes:
      - redis_data_dev:/data
    networks:
      - warely-network

  # Backend Service - Development
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    container_name: warely-backend-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/warely
      - MONGODB_URL=mongodb://admin:password@mongodb:27017/warely?authSource=admin
      - REDIS_URL=redis://redis:6379
      - DEBUG=backend:*
    volumes:
      - ./services/backend:/app
      - /app/node_modules
    command: ["pnpm", "dev"]
    depends_on:
      - postgres
      - mongodb
      - redis
    networks:
      - warely-network

  # Frontend Service - Development
  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    container_name: warely-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8080/api
      - VITE_AUTH_URL=http://localhost:8080/auth
    volumes:
      - ./services/frontend:/app
      - /app/node_modules
    command: ["pnpm", "dev", "--host", "0.0.0.0"]
    depends_on:
      - backend
    networks:
      - warely-network

volumes:
  postgres_data_dev:
  mongodb_data_dev:
  redis_data_dev:

networks:
  warely-network:
    driver: bridge
