# k8s/01-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: warely-config
  namespace: warely
data:
  # Database configuration
  POSTGRES_DB: "warely"
  POSTGRES_USER: "postgres"
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_DATABASE: "warely"

  # Application configuration
  NODE_ENV: "production"
  BACKEND_PORT: "5000"
  FRONTEND_PORT: "3000"
  AI_SERVICE_PORT: "6001"

  # Service URLs (internal cluster communication)
  POSTGRES_URL: "postgres:5432"
  MONGODB_URL: "mongodb://admin@mongodb:27017/warely?authSource=admin"
  REDIS_URL: "redis://redis:6379"
  AI_SERVICE_URL: "http://ai-service:6001"
