# k8s/02-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: warely-secrets
  namespace: warely
type: Opaque
stringData:
  # Database secrets
  postgres-password: "password"
  mongo-password: "password"

  # JWT secrets
  jwt-secret: "my-jwt-secret-key"
  jwt-refresh-secret: "my-jwt-refresh-secret-key"

  # Auth0 secrets
  auth0-domain: "dev-h6l82e421qmviw6y.us.auth0.com"
  auth0-client-id: "C4zQpl5hIpQg0yuuJ6pQ23hqstBW5I2O"
  auth0-client-secret: "AgV10k_pXxVQyT-JPg2clX4SXWpyZK_gUAZin-Cqju__Ke7fzcqaVhrXnLpWjsuZ"
  auth0-audience: "https://warely-api.com"
