# k8s/02-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: warely-secrets
  namespace: warely
type: Opaque
data:
  # Base64 encoded values (echo -n 'password' | base64)
  postgres-password: cGFzc3dvcmQ= # password
  mongo-password: cGFzc3dvcmQ= # password
  jwt-secret: bXktand0LXNlY3JldC1rZXk= # my-jwt-secret-key
  auth0-client-secret: eW91ci1hdXRoMC1jbGllbnQtc2VjcmV0 # your-auth0-client-secret
