# k8s/07-backend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: warely
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: warely-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: warely-secrets
                  key: postgres-password

            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: warely-secrets
                  key: mongo-password

            - name: DATABASE_URL
              value: "postgresql://postgres:$(POSTGRES_PASSWORD)@postgres:5432/warely"
            - name: MONGODB_URL
              value: "mongodb://admin:$(MONGO_PASSWORD)@mongodb:27017/warely?authSource=admin"
            - name: REDIS_URL
              value: "redis://redis:6379"

            # Application settings (same as before)
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "5000"

            # Auth0 configuration from Secrets
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: warely-secrets
                  key: auth0-domain
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: warely-secrets
                  key: auth0-client-id
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: warely-secrets
                  key: auth0-client-secret
            - name: AUTH0_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: warely-secrets
                  key: auth0-audience

            # JWT secrets from Secrets
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: warely-secrets
                  key: jwt-secret
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: warely-secrets
                  key: jwt-refresh-secret

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: warely
  labels:
    app: backend
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
