# k8s/07-backend-low-resources.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: warely
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: warely-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:password@postgres:5432/warely"
            - name: MONGODB_URL
              value: "mongodb://admin:password@mongodb:27017/warely?authSource=admin"
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "5000"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: warely
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
