# k8s/08-ai-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  namespace: warely
  labels:
    app: ai-service
    component: ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
        component: ai
    spec:
      containers:
        - name: ai-service
          image: warely-ai-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 6001
              name: http
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: warely-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: warely-config
                  key: AI_SERVICE_PORT
            - name: MONGODB_URL
              value: "mongodb://admin:$(MONGO_PASSWORD)@mongodb:27017/warely?authSource=admin"
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: warely-secrets
                  key: mongo-password
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: warely-config
                  key: REDIS_URL
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 6001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 6001
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: warely
  labels:
    app: ai-service
spec:
  type: ClusterIP
  selector:
    app: ai-service
  ports:
    - port: 6001
      targetPort: 6001
      protocol: TCP
      name: http
